/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.huaracheriamx;

import com.formdev.flatlaf.FlatLightLaf;
import com.mycompany.interfaces.DAOHuaracheTejido;
import com.mycompany.interfaces.DAOPrestamoPersonal;
import com.mycompany.models.HuaracheTejido;
import com.mycompany.models.ModeloTejido;
import com.mycompany.models.PrestamoPersonal;
import com.mycompany.utils.Utils;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor
 */
public class MuestraPrestamosPersonal extends javax.swing.JFrame {

    private int idModeloTejidoSeleccionado;
    private float sueldoPorLiquidar;
    private float totalPagoParesTejidos;
    private int idPersonalIngresado;
    private float sumaMontoPrestamo;

    /**
     * Creates new form MuestraHuaracheTejido
     */
    public MuestraPrestamosPersonal() {
        initComponents();
        LoadMuestraPrestamosPersonal();
        SetDate();
        SetHora();
        Bienvenida();
    }

    public MuestraPrestamosPersonal(int idPersonal) {
        initComponents();
        idPersonalIngresado = idPersonal;
        LoadMuestraPrestamosPersonal();
        SetDate();
        SetHora();
        Bienvenida();
    }

    private void LoadMuestraPrestamosPersonal() {
        //Se muestra el listado de los registros en la tabla
        try {
            DAOPrestamoPersonal dao = new DAOPrestamoPersonalImpl();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            dao.listar(idPersonalIngresado).forEach((d) -> model.addRow(new Object[]{d.getIdPrestamo(), d.getMontoPrestamo(), d.getStatus(), d.getFechaRegistro(), d.getIdPersonal()}));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

    }

    //Método para obtener la fecha actual del sistema
    private void SetDate() {
        // Obtener la fecha actual
        Date fechaActual = new Date();
        // Crear un formato para la fecha
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        // Obtener la fecha formateada como un String
        String fechaFormateada = formatoFecha.format(fechaActual);
        // Mostrar la fecha en el JLabel
        fechaLbl.setText(fechaFormateada);
    }
    
    //Método para obtener la hora actual del sistema
    private void SetHora() {
        // Configurar la zona horaria de México
        ZoneId zonaMexico = ZoneId.of("America/Mexico_City");

        // Actualizar la hora cada segundo
        Timer timer = new Timer(1000, e -> {
            LocalTime horaActual = LocalTime.now(zonaMexico);
            String horaFormateada = horaActual.format(DateTimeFormatter.ofPattern("hh:mm:ss a"));
            horaLbl.setText(horaFormateada);
        });
        timer.start();
    }

    //Método para mostrar el nombre el personal que ingreso
    private void Bienvenida() {
        String nombre = "";
        String aPaterno = "";
        String aMaterno = "";
        try {
            DAOHuaracheTejido dao = new DAOHuaracheTejidoImpl();
            nombre = dao.obtenerNombrePersonalIngresado(idPersonalIngresado);
            aPaterno = dao.obtenerApellidoPaternoTrabajador(idPersonalIngresado);
            aMaterno = dao.obtenerApellidoMaternoTrabajador(idPersonalIngresado);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        bienvenidaLbl.setText("Bienvenid@, " + nombre + " " + aPaterno + " " + aMaterno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        horaLbl = new javax.swing.JLabel();
        bienvenidaLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        nombreLbl1 = new javax.swing.JLabel();
        montoPrestamoTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        registrarBtn = new javax.swing.JButton();
        registrarBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(19, 39, 142));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        horaLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        horaLbl.setForeground(new java.awt.Color(255, 255, 255));
        horaLbl.setText("Hora");
        jPanel2.add(horaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, -1, -1));

        bienvenidaLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bienvenidaLbl.setForeground(new java.awt.Color(255, 255, 255));
        bienvenidaLbl.setText("Bienvenido");
        jPanel2.add(bienvenidaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hora:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, -1, -1));

        fechaLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fechaLbl.setForeground(new java.awt.Color(255, 255, 255));
        fechaLbl.setText("Fecha");
        jPanel2.add(fechaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Solicitud de prestamos");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        title.setPreferredSize(new java.awt.Dimension(215, 32));

        nombreLbl1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nombreLbl1.setText("Ingrese la monto del prestamo a solicitar:");

        montoPrestamoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Monto del préstamo", "Status", "Fecha de registro", "ID_Personal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        registrarBtn.setBackground(new java.awt.Color(51, 204, 255));
        registrarBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registrarBtn.setForeground(new java.awt.Color(255, 255, 255));
        registrarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enviar.png"))); // NOI18N
        registrarBtn.setText("Enviar ");
        registrarBtn.setBorderPainted(false);
        registrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarBtn.setFocusPainted(false);
        registrarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        registrarBtn.setIconTextGap(15);
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });

        registrarBtn1.setBackground(new java.awt.Color(255, 153, 51));
        registrarBtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registrarBtn1.setForeground(new java.awt.Color(255, 255, 255));
        registrarBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha.png"))); // NOI18N
        registrarBtn1.setText("Regresar");
        registrarBtn1.setBorderPainted(false);
        registrarBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarBtn1.setFocusPainted(false);
        registrarBtn1.setIconTextGap(15);
        registrarBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addComponent(nombreLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(montoPrestamoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(registrarBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(registrarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(nombreLbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(montoPrestamoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(registrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(registrarBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(10, 10, 10)))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed

        //Código mediante el cual se obtiene el formato de fecha
        Date fechaActual = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String fechaActualString = formato.format(fechaActual);

        //Se extraen los datos ingresados por el usuario mediante la interfaz grafica
        String cantidadPrestamoSolicitado = montoPrestamoTxt.getText();

        //Validaciones para los campos
        // Se pone el nombre de la variable y con la función isEmpty() se evalua si esta vacia
        if (cantidadPrestamoSolicitado.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            // Posiciona el cursor en el campo nombre
            montoPrestamoTxt.requestFocus();
            return;
        } else if (!Utils.isNumeric(cantidadPrestamoSolicitado)) {
            javax.swing.JOptionPane.showMessageDialog(this, "El campo monto del préstamo debe contener números enteros. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            montoPrestamoTxt.requestFocus();
            return;
        }

        //Se convierte en float el monto del préstamo a solicitar
        float cantPrestamoSolicitado = Float.parseFloat(cantidadPrestamoSolicitado);

        //Se obtiene el sueldo por liquidar del personal que ingreso y la suma de los prestamos solicitados con status "Aprobado"
        try {
            DAOPrestamoPersonal dao = new DAOPrestamoPersonalImpl();
            sueldoPorLiquidar = dao.obtenerSueldoPorPagar(idPersonalIngresado);
            sumaMontoPrestamo = dao.obtenerPrestamosAprovados(idPersonalIngresado);
        } catch (Exception e) {
            sueldoPorLiquidar = 0;
            sumaMontoPrestamo = 0;
            System.out.println(e.getMessage());
        }

        float restaPrestamoSueldo = sueldoPorLiquidar - sumaMontoPrestamo;
        if (restaPrestamoSueldo < cantPrestamoSolicitado) {
            javax.swing.JOptionPane.showMessageDialog(this, "El monto de solicitud del préstamo debe ser menor o igual a " + restaPrestamoSueldo + ". \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        PrestamoPersonal prestPersonal = new PrestamoPersonal();
        prestPersonal.setMontoPrestamo(cantPrestamoSolicitado);
        prestPersonal.setFechaRegistro(fechaActualString);
        prestPersonal.setIdPersonal(idPersonalIngresado);
        prestPersonal.setStatus("Pendiente");

        try {
            DAOPrestamoPersonal dao = new DAOPrestamoPersonalImpl();
            dao.registrar(prestPersonal);

            javax.swing.JOptionPane.showMessageDialog(this, "La solicitud del préstamo se envió exitosamente. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            //Se vuelve a cargar la tabla con el nuevo registro
                LoadMuestraPrestamosPersonal();
            //Ya que se realizo el registro se limpian todas las cajas de texto
            montoPrestamoTxt.setText("");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al enviar la solicitud del préstamo. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_registrarBtnActionPerformed

    private void registrarBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtn1ActionPerformed
        MuestraHuaracheTejido huarTejido = new MuestraHuaracheTejido(idPersonalIngresado);
        javax.swing.SwingUtilities.getWindowAncestor(getContentPane()).dispose();
        huarTejido.setVisible(true);
    }//GEN-LAST:event_registrarBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
                FlatLightLaf.setup();
UIManager.put( "Button.arc", 999 );
        UIManager.put( "TextComponent.arc", 999 );
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuestraPrestamosPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenidaLbl;
    private javax.swing.JLabel fechaLbl;
    private javax.swing.JLabel horaLbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField montoPrestamoTxt;
    private javax.swing.JLabel nombreLbl1;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JButton registrarBtn1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
