/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.views;

import com.mycompany.huaracheriamx.DAOPrestamoPersonalImpl;
import com.mycompany.interfaces.DAOPrestamoPersonal;
import com.mycompany.models.PrestamoPersonal;
import com.mycompany.utils.Utils;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Victor
 */


public class RegistroPrestamoPersonal extends javax.swing.JPanel {

    private int idModeloTejidoSeleccionado;
    private float sueldoPorLiquidar;
    private float totalPagoParesTejidos;
    private int idPersonalIngresado;
    private float sumaMontoPrestamo;
    
    /**
     * Creates new form CaracteristicasHuarache
     */
    public RegistroPrestamoPersonal(int idPersonal) {
        initComponents();
        idPersonalIngresado = idPersonal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        montoPrestamoTxt = new javax.swing.JTextField();
        statusLbl = new javax.swing.JLabel();
        montoPrestamoLbl = new javax.swing.JLabel();
        registrarBtn = new javax.swing.JButton();
        statusComboBox = new javax.swing.JComboBox<>();
        image1 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rp2.png"))); // NOI18N

        title2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Registro de préstamos");
        title2.setPreferredSize(new java.awt.Dimension(215, 32));

        montoPrestamoTxt.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        montoPrestamoTxt.setPreferredSize(new java.awt.Dimension(6, 20));

        statusLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        statusLbl.setText("Status");

        montoPrestamoLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        montoPrestamoLbl.setText("Monto del préstamo");

        registrarBtn.setBackground(new java.awt.Color(18, 90, 173));
        registrarBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registrarBtn.setForeground(new java.awt.Color(255, 255, 255));
        registrarBtn.setText("Registrar");
        registrarBtn.setBorderPainted(false);
        registrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });

        statusComboBox.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "          ", "Pendiente", "Aprobado", "Rechazado" }));

        image1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rp.png"))); // NOI18N

        jSeparator14.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator14.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator14.setPreferredSize(new java.awt.Dimension(200, 10));

        jSeparator15.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator15.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator15.setPreferredSize(new java.awt.Dimension(200, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(246, 246, 246))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(montoPrestamoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(161, 161, 161))
                            .addComponent(montoPrestamoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(statusLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(263, 263, 263))
                            .addComponent(statusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(registrarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(montoPrestamoLbl)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(montoPrestamoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(statusLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(image1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(registrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(165, 165, 165))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed
        //Código mediante el cual se obtiene el formato de fecha
        Date fechaActual = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String fechaActualString = formato.format(fechaActual);

        //Se extraen los datos ingresados por el usuario mediante la interfaz grafica
        String cantidadPrestamoSolicitado = montoPrestamoTxt.getText();
        
        //Se obtiene el valor seleccionado del comboBox de la interfaz grafica
        String valorSeleccionadoComboBox = (String) statusComboBox.getSelectedItem();

        //Validaciones para los campos
        // Se pone el nombre de la variable y con la función isEmpty() se evalua si esta vacia
        if (cantidadPrestamoSolicitado.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            // Posiciona el cursor en el campo nombre
            montoPrestamoTxt.requestFocus();
            return;
        }else if (valorSeleccionadoComboBox == "          ") {
            javax.swing.JOptionPane.showMessageDialog(this, "No ha seleccionado ninguna opción en el apartado Status. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            statusComboBox.requestFocus();
            return;
        } else if (!Utils.isNumeric(cantidadPrestamoSolicitado)) {
            javax.swing.JOptionPane.showMessageDialog(this, "El campo monto del préstamo debe contener números enteros. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            montoPrestamoTxt.requestFocus();
            return;
        }

        //Se convierte en float el monto del préstamo a solicitar
        float cantPrestamoSolicitado = Float.parseFloat(cantidadPrestamoSolicitado);

        //Se obtiene el sueldo por liquidar del personal que ingreso y la suma de los prestamos solicitados con status "Aprobado"
        try {
            DAOPrestamoPersonal dao = new DAOPrestamoPersonalImpl();
            sueldoPorLiquidar = dao.obtenerSueldoPorPagar(idPersonalIngresado);
            sumaMontoPrestamo = dao.obtenerPrestamosAprovados(idPersonalIngresado);
        } catch (Exception e) {
            sueldoPorLiquidar = 0;
            sumaMontoPrestamo = 0;
            System.out.println(e.getMessage());
        }

        float restaPrestamoSueldo = sueldoPorLiquidar - sumaMontoPrestamo;
        if (restaPrestamoSueldo < cantPrestamoSolicitado) {
            javax.swing.JOptionPane.showMessageDialog(this, "El monto del préstamo debe ser menor o igual a " + restaPrestamoSueldo + ". \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        PrestamoPersonal prestPersonal = new PrestamoPersonal();
        prestPersonal.setMontoPrestamo(cantPrestamoSolicitado);
        prestPersonal.setFechaRegistro(fechaActualString);
        prestPersonal.setIdPersonal(idPersonalIngresado);
        prestPersonal.setStatus(valorSeleccionadoComboBox);

        try {
            DAOPrestamoPersonal dao = new DAOPrestamoPersonalImpl();
            dao.registrar(prestPersonal);

            javax.swing.JOptionPane.showMessageDialog(this, "El registro del préstamo se realizó exitosamente. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            //Se vuelve a cargar la tabla con el nuevo registro
//                LoadMuestraHuaracheTejido();
            //Ya que se realizo el registro se limpian todas las cajas de texto
            montoPrestamoTxt.setText("");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al realizar el registro del préstamo. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_registrarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JLabel image1;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JLabel montoPrestamoLbl;
    private javax.swing.JTextField montoPrestamoTxt;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
