/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.views;

import com.mycompany.huaracheriamx.DAOClienteImpl;
import com.mycompany.interfaces.DAOCliente;
import com.mycompany.models.Clientes;
import com.mycompany.utils.Utils;
import java.awt.Color;
import java.text.SimpleDateFormat;
import static java.time.LocalDateTime.now;
import java.util.Date;

/**
 *
 * @author Victor
 */
public class RegistroClientes extends javax.swing.JPanel {

    /**
     * Creates new form Returns
     */
    public RegistroClientes() {
        initComponents();
        InitStyles();
    }
    
    private void InitStyles(){
        nombreTxt.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del cliente.");
        aPaternoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido paterno del cliente.");
        aMaternoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido materno del cliente.");
        telefonoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el número de teléfono del cliente.");
        correoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el correo del cliente.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        nombreLbl1 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        aMaternoTxt = new javax.swing.JTextField();
        autorLbl1 = new javax.swing.JLabel();
        aPaternoTxt = new javax.swing.JTextField();
        aPaternoLbl1 = new javax.swing.JLabel();
        correoTxt = new javax.swing.JTextField();
        correoLbl1 = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        telefonoLbl1 = new javax.swing.JLabel();
        button1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(790, 590));

        bg1.setBackground(new java.awt.Color(255, 255, 255));
        bg1.setPreferredSize(new java.awt.Dimension(790, 590));

        title1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Registro de Clientes");
        title1.setPreferredSize(new java.awt.Dimension(215, 32));

        nombreLbl1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nombreLbl1.setText("Nombre");

        nombreTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        aMaternoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        autorLbl1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        autorLbl1.setText("Apellido Materno");

        aPaternoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        aPaternoLbl1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        aPaternoLbl1.setText("Apellido paterno");
        aPaternoLbl1.setPreferredSize(new java.awt.Dimension(80, 20));

        correoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        correoLbl1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        correoLbl1.setText("Correo");

        telefonoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        telefonoLbl1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        telefonoLbl1.setText("Teléfono");
        telefonoLbl1.setPreferredSize(new java.awt.Dimension(80, 20));

        button1.setBackground(new java.awt.Color(18, 90, 173));
        button1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Registrar");
        button1.setBorderPainted(false);
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc2.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator4.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));

        jSeparator5.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));

        javax.swing.GroupLayout bg1Layout = new javax.swing.GroupLayout(bg1);
        bg1.setLayout(bg1Layout);
        bg1Layout.setHorizontalGroup(
            bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg1Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(270, 270, 270))
            .addGroup(bg1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg1Layout.createSequentialGroup()
                        .addComponent(nombreLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(266, 266, 266))
                    .addComponent(nombreTxt)
                    .addGroup(bg1Layout.createSequentialGroup()
                        .addComponent(aPaternoLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(136, 136, 136))
                    .addComponent(aPaternoTxt)
                    .addComponent(aMaternoTxt)
                    .addGroup(bg1Layout.createSequentialGroup()
                        .addComponent(telefonoLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(92, 92, 92))
                    .addComponent(telefonoTxt)
                    .addGroup(bg1Layout.createSequentialGroup()
                        .addComponent(correoLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(253, 253, 253))
                    .addComponent(correoTxt)
                    .addGroup(bg1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(bg1Layout.createSequentialGroup()
                        .addComponent(autorLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(151, 151, 151)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        bg1Layout.setVerticalGroup(
            bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg1Layout.createSequentialGroup()
                .addGroup(bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bg1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE)
                        .addGroup(bg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bg1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bg1Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bg1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(nombreLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(aPaternoLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addGap(6, 6, 6)
                                .addComponent(aPaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(autorLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                .addGap(0, 0, 0)
                                .addComponent(aMaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(telefonoLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addGap(6, 6, 6)
                                .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(correoLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10)
                                .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bg1Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addGap(52, 52, 52)))))
                .addGap(98, 98, 98))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //Botón para hacer un registro de clientes
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        //Código mediante el cual se obtiene el formato de fecha y hora actual
        Date now = new Date();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String nowString = format.format(now);

        //Se extraen los datos ingresados por el usuario mediante la interfaz grafica
        String nombre = nombreTxt.getText();
        String apaterno = aPaternoTxt.getText();
        String amaterno = aMaternoTxt.getText();
        String telefono = telefonoTxt.getText();
        String correo = correoTxt.getText();

        //Validaciones para los campos
        // Se pone el nombre de la variable y con la función isEmpty() se evalua si esta vacia
        if (nombre.isEmpty() || apaterno.isEmpty() || amaterno.isEmpty() || telefono.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            // Posiciona el cursor en el campo nombre
            nombreTxt.requestFocus();
            return;
        }else if (!Utils.isNumeric(telefono)) {
            javax.swing.JOptionPane.showMessageDialog(this, "El campo teléfono debe contener números enteros. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            telefonoTxt.requestFocus();
            return;
        }
        
        

        //Se asignan los valores para registrarlos en la base de datos
        Clientes cliente = new Clientes();
        cliente.setNombre(nombre);
        cliente.setApaterno(apaterno);
        cliente.setAmaterno(amaterno);
        cliente.setFechaHoraRegistro(nowString);
        cliente.setCorreo(correo);
        cliente.setTelefono(telefono);

        try {
            DAOCliente dao = new DAOClienteImpl();
            dao.registrar(cliente);

            javax.swing.JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            //Ya que se realizo el registro se limpian todas las cajas de texto
            nombreTxt.setText("");
            aPaternoTxt.setText("");
            aMaternoTxt.setText("");
            telefonoTxt.setText("");
            correoTxt.setText("");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar al cliente. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_button1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aMaternoTxt;
    private javax.swing.JLabel aPaternoLbl1;
    private javax.swing.JTextField aPaternoTxt;
    private javax.swing.JLabel autorLbl1;
    private javax.swing.JPanel bg1;
    private javax.swing.JButton button1;
    private javax.swing.JLabel correoLbl1;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel nombreLbl1;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel telefonoLbl1;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
