/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.views;

import com.mycompany.huaracheriamx.DAOPersonalImpl;
import com.mycompany.interfaces.DAOPersonal;
import com.mycompany.models.Personal;
import com.mycompany.utils.Utils;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Victor
 */
public class RegistroPersonal extends javax.swing.JPanel {

    /**
     * Creates new form Returns
     */
    public RegistroPersonal() {
        initComponents();
        InitStyles();
    }
    
    private void InitStyles(){
        nombreTxt.putClientProperty("JTextField.placeholderText", "Ingrese el nombre del trabajador.");
        aPaternoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido paterno del trabajador.");
        aMaternoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el apellido materno del trabajador.");
        telefonoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el número de teléfono del trabajador.");
        correoTxt.putClientProperty("JTextField.placeholderText", "Ingrese el correo del trabajador.");
        usuarioTxt.putClientProperty("JTextField.placeholderText", "Ingrese el usuario del trabajador.");
        passwordTxt.putClientProperty("JTextField.placeholderText", "Ingrese la contraseña del trabajador.");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        title = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        aMaternoTxt = new javax.swing.JTextField();
        autorLbl = new javax.swing.JLabel();
        aPaternoTxt = new javax.swing.JTextField();
        aPaternoLbl = new javax.swing.JLabel();
        correoTxt = new javax.swing.JTextField();
        correoLbl = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        telefonoLbl = new javax.swing.JLabel();
        usuarioLbl = new javax.swing.JLabel();
        usuarioTxt = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        statusLbl = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        statusComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(790, 590));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(790, 590));

        jSeparator1.setBackground(new java.awt.Color(240, 240, 240));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Registro de Personal");
        title.setPreferredSize(new java.awt.Dimension(215, 32));

        nombreLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nombreLbl.setText("Nombre");

        nombreTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        aMaternoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        autorLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        autorLbl.setText("Apellido Materno");

        aPaternoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        aPaternoLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        aPaternoLbl.setText("Apellido paterno");
        aPaternoLbl.setPreferredSize(new java.awt.Dimension(80, 20));

        correoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        correoLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        correoLbl.setText("Correo");

        telefonoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        telefonoLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        telefonoLbl.setText("Teléfono");
        telefonoLbl.setPreferredSize(new java.awt.Dimension(80, 20));

        usuarioLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        usuarioLbl.setText("Usuario");

        usuarioTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuarioTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTxtActionPerformed(evt);
            }
        });

        passwordLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        passwordLbl.setText("Contraseña");
        passwordLbl.setPreferredSize(new java.awt.Dimension(80, 20));

        passwordTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        statusLbl.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        statusLbl.setText("Status");

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(255, 255, 255));
        button.setText("Registrar");
        button.setBorderPainted(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.setFocusPainted(false);
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        statusComboBox.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "          ", "Activo", "Inactivo" }));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(nombreLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(241, 241, 241))
                            .addComponent(nombreTxt)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(aPaternoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(136, 136, 136))
                            .addComponent(aPaternoTxt)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(autorLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(170, 170, 170))
                            .addComponent(aMaternoTxt)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(telefonoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(92, 92, 92))
                            .addComponent(telefonoTxt)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(correoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(253, 253, 253))
                            .addComponent(correoTxt))
                        .addGap(56, 56, 56)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(usuarioLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(236, 236, 236))
                            .addComponent(usuarioTxt)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(passwordLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(175, 175, 175))
                            .addComponent(passwordTxt)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(statusLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(248, 248, 248))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(statusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(125, 125, 125))
                            .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(189, 189, 189)))
                .addGap(55, 55, 55))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(nombreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(aPaternoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(aPaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(autorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(aMaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(telefonoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(correoLbl)
                        .addGap(8, 8, 8)
                        .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(usuarioLbl)
                        .addGap(8, 8, 8)
                        .addComponent(usuarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(passwordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(statusLbl)
                        .addGap(8, 8, 8)
                        .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTxtActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        //Código mediante el cual se obtiene el formato de fecha
        Date fechaActual = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String fechaActualString = formato.format(fechaActual);
        
        //Se obtiene el valor seleccionado del comboBox de la interfaz grafica
        String valorSeleccionadoComboBox = (String) statusComboBox.getSelectedItem();
        
        //Se extraen los datos ingresados por el usuario mediante la interfaz grafica
        String nombre = nombreTxt.getText();
        String apaterno = aPaternoTxt.getText();
        String amaterno = aMaternoTxt.getText();
        String telefono = telefonoTxt.getText();
        String correo = correoTxt.getText();
        String usuario = usuarioTxt.getText();
        String password = passwordTxt.getText();
        
        //Validaciones para los campos
        // Se pone el nombre de la variable y con la función isEmpty() se evalua si esta vacia
        if (nombre.isEmpty() || apaterno.isEmpty() || amaterno.isEmpty() || telefono.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            // Posiciona el cursor en el campo nombre
            nombreTxt.requestFocus();
            return;
        }else if (valorSeleccionadoComboBox == "          ") {
            javax.swing.JOptionPane.showMessageDialog(this, "No ha seleccionado ninguna opción en el apartado Status. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            statusComboBox.requestFocus();
            return;
        }else if (!Utils.isNumeric(telefono)) {
            javax.swing.JOptionPane.showMessageDialog(this, "El campo teléfono debe contener números enteros. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            telefonoTxt.requestFocus();
            return;
        }
        
        Personal persona = new Personal();
        persona.setNombre(nombre);
        persona.setApaterno(apaterno);
        persona.setAmaterno(amaterno);
        persona.setTelefono(telefono);
        persona.setCorreo(correo);
        persona.setFechaRegistro(fechaActualString);
        persona.setUsuario(usuario);
        persona.setPassword(password);
        persona.setStatus(valorSeleccionadoComboBox);
        
        try {
            DAOPersonal dao = new DAOPersonalImpl();
            dao.registrar(persona);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Trabajador registrado exitosamente. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            //Ya que se realizo el registro se limpian todas las cajas de texto
            nombreTxt.setText("");
            aPaternoTxt.setText("");
            aMaternoTxt.setText("");
            telefonoTxt.setText("");
            correoTxt.setText("");
            usuarioTxt.setText("");
            passwordTxt.setText("");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar al trabajador. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aMaternoTxt;
    private javax.swing.JLabel aPaternoLbl;
    private javax.swing.JTextField aPaternoTxt;
    private javax.swing.JLabel autorLbl;
    private javax.swing.JPanel bg;
    private javax.swing.JButton button;
    private javax.swing.JLabel correoLbl;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JLabel telefonoLbl;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JLabel title;
    private javax.swing.JLabel usuarioLbl;
    private javax.swing.JTextField usuarioTxt;
    // End of variables declaration//GEN-END:variables
}
